#rm(list = ls())
library(MASS)
library(dlm)
library(reshape)
library(tidyr)

library(glmnet)
library(zoo)
library(openxlsx)
library(lubridate)
library(tidyverse)
library(dplyr)
library(car)
library(splitstackshape)
library(mefa)
library(foreach)
library(doParallel)
library(data.table)
library(bayesreg)
library(asbio)
library(caret)
library(forecast)
library(loo)
library(magrittr)
library(cv)

numCores <- detectCores()
registerDoParallel(numCores-5)  # use multicore, set to the number of our cores

# conflicted::conflict_prefer("loadings", "stats")
# conflicted::conflict_prefer("expand", "reshape")
# conflicted::conflict_prefer("bdiag", "glmnet")
# conflicted::conflict_prefer("as.Date", "base")
# conflicted::conflict_prefer("as.Date.numeric", "base")
# conflicted::conflict_prefer("stamp", "lubridate")
# conflicted::conflict_prefer("date", "dplyr")
# conflicted::conflict_prefer("intersect", "dplyr")
# conflicted::conflict_prefer("setdiff", "dplyr")
# conflicted::conflict_prefer("union", "dplyr")
# conflicted::conflict_prefer("filter", "dplyr")
# conflicted::conflict_prefer("lag", "dplyr")
# conflicted::conflict_prefer("pack", "tidyr")
# conflicted::conflict_prefer("rename", "dplyr")
# conflicted::conflict_prefer("select", "dplyr")
# conflicted::conflict_prefer("unpack", "tidyr")
# conflicted::conflict_prefer("recode", "dplyr")
# conflicted::conflict_prefer("some", "mefa")
# conflicted::conflict_prefer("melt", "reshape")
# conflicted::conflict_prefer("accumulate", "foreach")
# conflicted::conflict_prefer("when", "foreach")
# conflicted::conflict_prefer("between", "data.table")
# conflicted::conflict_prefer("first", "data.table")
# conflicted::conflict_prefer("last", "data.table")
# conflicted::conflict_prefer("transpose", "data.table")
# conflicted::conflict_prefer("hour", "data.table")
# conflicted::conflict_prefer("isoweek", "data.table")
# conflicted::conflict_prefer("mday", "data.table")
# conflicted::conflict_prefer("minute", "data.table")
# conflicted::conflict_prefer("month", "data.table")
# conflicted::conflict_prefer("quarter", "data.table")
# conflicted::conflict_prefer("second", "data.table")
# conflicted::conflict_prefer("wday", "data.table")
# conflicted::conflict_prefer("week", "data.table")
# conflicted::conflict_prefer("yday", "data.table")
# conflicted::conflict_prefer("year", "data.table")
# conflicted::conflict_prefer("pm", "lubridate")
# conflicted::conflict_prefer("lift", "caret")







